# Generated by Django 5.2.6 on 2025-10-09 19:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("product", "Product"),
                            ("order", "Order"),
                            ("supplier", "Supplier"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("user_registered", "New User Registered"),
                            ("user_profile_updated", "User Profile Updated"),
                            ("user_password_updated", "User Password Updated"),
                            ("user_deleted", "User Deleted"),
                            ("group_created", "New Group Created"),
                            ("group_updated", "Group Updated"),
                            ("group_deleted", "Group Deleted"),
                            ("low_stock", "Product Stock is Low"),
                            ("out_of_stock", "Product Out of Stock"),
                            ("stock_updated", "Stock Quantity Updated"),
                            ("new_order", "New Order Received"),
                            ("order_shipped", "Order Shipped"),
                            ("order_delivered", "Order Delivered"),
                            ("supplier_added", "New Supplier Added"),
                            ("supplier_payment_due", "Supplier Payment Due"),
                            ("system_error", "System Error"),
                            ("backup_completed", "Backup Completed"),
                        ],
                        max_length=55,
                    ),
                ),
                ("message", models.TextField()),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="dashboard_n_user_id_b572f4_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="dashboard_n_notific_47e787_idx",
                    ),
                    models.Index(
                        fields=["category"], name="dashboard_n_categor_416221_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="dashboard_n_created_526fd9_idx"
                    ),
                ],
            },
        ),
    ]
