# Generated by Django 5.2.6 on 2025-10-16 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_product"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="supplier",
            options={
                "ordering": ["-created_at"],
                "permissions": [("ledger_supplier", "Can view supplier ledger")],
                "verbose_name": "Supplier",
                "verbose_name_plural": "Suppliers",
            },
        ),
    ]
