# Generated by Django 5.2.6 on 2025-10-18 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_alter_supplier_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("Net 15", "Net 15 days"),
                    ("Net 30", "Net 30 days"),
                    ("COD", "Cash on Delivery"),
                    ("Advance 50%", "Advance 50%"),
                    ("Imediate", "Imediate"),
                ],
                default="Imediate",
                max_length=100,
            ),
        ),
    ]
